# Generated by Django 4.1.6 on 2023-02-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_rename_courseid_exam_courseid_remove_exam_chapterno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChapterNumber', models.IntegerField()),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course')),
            ],
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.AlterField(
            model_name='question',
            name='chapterNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.chapter'),
        ),
    ]
