# Generated by Django 4.1.6 on 2023-02-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chapterNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.chapter'),
        ),
    ]
